### ISSUE TITLE
Building nv-codec-headers  fails

### ISSUE THREAD

**Issue by jonno85uk** [snapcrafters/ffmpeg#27]
Building nv-codec-headers 
sed 's#@@PREFIX@@#/usr#' ffnvcodec.pc.in > ffnvcodec.pc
install -m 0755 -d '/usr/include/ffnvcodec'
install: cannot change permissions of ‘/usr/include/ffnvcodec’: No such file or directory
Makefile:14: recipe for target 'install' failed
make: *** [install] Error 1
Failed to run 'override-build': Exit code was 2.

Ubuntu 18.04 amd64, snapcraft, version 2.43.1+18.4. Fresh clone. Called 'snapcraft' with no arguments.

**Comment by flexiondotorg** [comment]
As a general rule, you should be building snaps in an Ubuntu 16.04 container or VM. We are improving `snapcraft` so that it will "do the right thing" by default. But, for now, you can build your snaps in LXD. See these instructions:

  * https://docs.snapcraft.io/build-on-lxd/4157

The ffmpeg snap builds correctly, I have rebuilt it dozens of times this weekend. If you have any further difficultly building a snap please come and join us in the [Snapcraft Discource](https://forum.snapcraft.io) and ask any questions you might have there :smiley:

**Comment by jonno85uk** [comment]
Ah. I forgot about 16.04. Seems I will have to setup a container.
Cheers!
